### ISSUE TITLE
Storing monitor live streams in MP4 format

### ISSUE THREAD

**Issue by JoeAlamo** [Whytehorse/empathy#1]
Hey, apologies for the odd way of getting in contact.

I've been reading through https://github.com/ZoneMinder/ZoneMinder/issues/452 and https://github.com/ZoneMinder/ZoneMinder/issues/39. In there you said to accomplish this you stopped using ZM and used another solution.

Would you mind briefly explaining your solution?

I can be contacted here or via joe@sgpconsulting.co.uk.

Many thanks!

**Comment by Whytehorse** [comment]
I just use avconv(ffmpeg) at the command line. There's a new thread
somewhere where we're trying to get ZM going with h264 but the progress
is slow

**Comment by moeiscool** [comment]
_just for anyone who stops by here :_

about 3 years ago i needed cctv. I found zoneminder, tried to edit it to my liking, but found i was fixing it more than editing it.

Not to mention mp4 recording feature isn't actually part of the master branch (which is kind of lol, since its a cctv program and its already been about 3 years or more since it was suggested). Its literally just adapting the ffmpeg command lol.

**So i found the solution!**

> If you want something done right, do it yourself.

I present to you Shinobi! https://github.com/moeiscool/Shinobi

<img src="https://github.com/moeiscool/Shinobi/blob/master/web/libs/img/demo.gif?raw=true">
